import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from anthropic import Anthropic
from dotenv import load_dotenv
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib import colors
import plotly.io as pio
import tempfile
import io
load_dotenv()
client = Anthropic()

# ── PAGE CONFIG ──
st.set_page_config(
    page_title="PulseReport",
    page_icon="📊",
    layout="wide"
)

# ── DEMO DATA ──
def load_demo_data():
    revenue_data = pd.DataFrame({
        "Month": ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
        "Enterprise_Actual": [1200,1250,1300,1280,1350,1400,1380,1420,1500,1480,1550,1600],
        "Enterprise_Budget": [1150,1200,1250,1300,1350,1400,1400,1450,1500,1550,1600,1650],
        "SMB_Actual":        [800,820,810,850,870,890,860,880,920,910,940,970],
        "SMB_Budget":        [780,800,820,840,860,880,880,900,920,940,960,980],
        "Services_Actual":   [400,410,420,415,430,445,440,450,460,455,470,480],
        "Services_Budget":   [390,400,410,420,430,440,440,450,460,470,480,490],
    })

    expense_data = pd.DataFrame({
        "Month": ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
        "Headcount_Actual":  [900,910,920,915,930,940,935,945,960,955,965,975],
        "Headcount_Budget":  [920,920,930,930,940,940,940,950,960,960,970,970],
        "Marketing_Actual":  [200,210,220,215,225,230,228,235,240,238,245,250],
        "Marketing_Budget":  [210,210,220,220,230,230,230,240,240,250,250,260],
        "Operations_Actual": [150,155,158,153,160,165,163,167,172,170,175,178],
        "Operations_Budget": [155,155,160,160,165,165,165,170,170,175,175,180],
        "Tech_Actual":       [100,102,105,103,107,110,109,112,115,113,117,120],
        "Tech_Budget":       [100,105,105,110,110,115,115,115,120,120,125,125],
    })

    kpi_data = pd.DataFrame({
        "KPI": ["Gross Margin %", "EBITDA Margin %", "Headcount", "Revenue per Employee ($K)"],
        "Actual": [62.4, 18.2, 142, 184],
        "Budget": [61.0, 17.5, 145, 179],
        "Prior Month": [61.8, 17.9, 140, 181],
    })

    return revenue_data, expense_data, kpi_data
def generate_pdf(company_name, selected_month, revenue_df, expense_df, kpi_df, commentary):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=0.75*inch, leftMargin=0.75*inch,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title', parent=styles['Heading1'],
                                  fontSize=20, textColor=colors.HexColor('#2563EB'),
                                  spaceAfter=6)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'],
                                     fontSize=11, textColor=colors.grey, spaceAfter=20)
    section_style = ParagraphStyle('Section', parent=styles['Heading2'],
                                    fontSize=13, textColor=colors.HexColor('#1E3A5F'),
                                    spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle('Body', parent=styles['Normal'],
                                 fontSize=10, leading=15, spaceAfter=12)

    story = []

    # Header
    story.append(Paragraph(f"{company_name} — Monthly Business Review", title_style))
    story.append(Paragraph(f"Reporting Period: {selected_month} 2025  |  Generated by PulseReport", subtitle_style))

    # KPI Table
    story.append(Paragraph("Key Performance Indicators", section_style))
    kpi_table_data = [["KPI", "Actual", "Budget", "Variance"]]
    for _, row in kpi_df.iterrows():
        delta = round(row["Actual"] - row["Budget"], 1)
        kpi_table_data.append([row["KPI"], str(row["Actual"]), str(row["Budget"]), f"{delta:+}"])

    kpi_table = Table(kpi_table_data, colWidths=[3*inch, 1.2*inch, 1.2*inch, 1.2*inch])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563EB')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#F8FAFC'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 0.2*inch))

    # Revenue chart
    story.append(Paragraph("Revenue Performance", section_style))
    fig_rev = go.Figure()
    fig_rev.add_trace(go.Scatter(x=revenue_df["Month"], y=revenue_df["Total_Actual"],
        name="Actual", line=dict(color="#2563EB", width=3)))
    fig_rev.add_trace(go.Scatter(x=revenue_df["Month"], y=revenue_df["Total_Budget"],
        name="Budget", line=dict(color="#94A3B8", width=2, dash="dash")))
    fig_rev.update_layout(title="Total Revenue: Actual vs Budget ($K)",
        plot_bgcolor="white", paper_bgcolor="white", height=300, width=650)
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        pio.write_image(fig_rev, tmp.name, format="png")
        story.append(Image(tmp.name, width=6.5*inch, height=3*inch))

    story.append(Spacer(1, 0.2*inch))

    # Variance Table
    story.append(Paragraph("Variance Summary", section_style))
    latest_rev = revenue_df.iloc[-1]
    prior_rev = revenue_df.iloc[-2]

    var_headers = ["Line Item", "Actual ($K)", "Budget ($K)", "vs Budget ($K)", "vs Budget (%)"]
    var_rows = [
        ["Enterprise Revenue", latest_rev["Enterprise_Actual"], latest_rev["Enterprise_Budget"],
         latest_rev["Enterprise_Actual"] - latest_rev["Enterprise_Budget"],
         f"{((latest_rev['Enterprise_Actual']-latest_rev['Enterprise_Budget'])/latest_rev['Enterprise_Budget']*100):.1f}%"],
        ["SMB Revenue", latest_rev["SMB_Actual"], latest_rev["SMB_Budget"],
         latest_rev["SMB_Actual"] - latest_rev["SMB_Budget"],
         f"{((latest_rev['SMB_Actual']-latest_rev['SMB_Budget'])/latest_rev['SMB_Budget']*100):.1f}%"],
        ["Services Revenue", latest_rev["Services_Actual"], latest_rev["Services_Budget"],
         latest_rev["Services_Actual"] - latest_rev["Services_Budget"],
         f"{((latest_rev['Services_Actual']-latest_rev['Services_Budget'])/latest_rev['Services_Budget']*100):.1f}%"],
        ["Total Revenue", latest_rev["Total_Actual"], latest_rev["Total_Budget"],
         latest_rev["Total_Actual"] - latest_rev["Total_Budget"],
         f"{((latest_rev['Total_Actual']-latest_rev['Total_Budget'])/latest_rev['Total_Budget']*100):.1f}%"],
    ]

    var_table = Table([var_headers] + var_rows,
                      colWidths=[2.2*inch, 1.1*inch, 1.1*inch, 1.2*inch, 1.1*inch])
    var_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E3A5F')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#F8FAFC'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 7),
    ]))
    story.append(var_table)
    story.append(Spacer(1, 0.2*inch))

    # AI Commentary
    if commentary:
        story.append(Paragraph("AI-Generated Executive Commentary", section_style))
        for para in commentary.split('\n\n'):
            if para.strip():
                story.append(Paragraph(para.strip(), body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer
# ── SIDEBAR ──
st.sidebar.image("https://img.icons8.com/fluency/96/combo-chart.png", width=60)
st.sidebar.title("PulseReport")
st.sidebar.markdown("*AI-Powered Monthly Business Review*")
st.sidebar.divider()

data_source = st.sidebar.radio("Data Source", ["Demo Data", "Upload File", "Enter Manually"])
selected_month = st.sidebar.selectbox("Reporting Month", 
    ["January","February","March","April","May","June",
     "July","August","September","October","November","December"],
    index=9)
company_name = st.sidebar.text_input("Company Name", value="Apex Industries")

st.sidebar.divider()
st.sidebar.caption("Built by Caden Chergey")

# ── LOAD DATA ──
if data_source == "Demo Data":
    revenue_df, expense_df, kpi_df = load_demo_data()
    st.sidebar.success("Demo data loaded")

elif data_source == "Upload File":
    uploaded = st.sidebar.file_uploader("Upload Excel or CSV", type=["xlsx","csv"])
    if uploaded:
        if uploaded.name.endswith(".csv"):
            revenue_df = pd.read_csv(uploaded)
        else:
            revenue_df = pd.read_excel(uploaded)
        expense_df = pd.DataFrame()
        kpi_df = pd.DataFrame()
        st.sidebar.success("File loaded")
    else:
        st.info("Upload a file in the sidebar to get started.")
        st.stop()

else:
    st.info("Manual entry coming soon.")
    st.stop()

# ── HEADER ──
st.title(f"📊 {company_name} — Monthly Business Review")
st.subheader(f"Reporting Period: {selected_month} 2025")
st.divider()

# ── KPI SCORECARD ──
st.markdown("### Key Performance Indicators")
col1, col2, col3, col4 = st.columns(4)

for i, row in kpi_df.iterrows():
    delta = round(row["Actual"] - row["Budget"], 1)
    cols = [col1, col2, col3, col4]
    cols[i].metric(
        label=row["KPI"],
        value=row["Actual"],
        delta=f"{delta:+} vs Budget"
    )

st.divider()

# ── REVENUE CHARTS ──
st.markdown("### Revenue Performance")
col_left, col_right = st.columns(2)

with col_left:
    revenue_df["Total_Actual"] = revenue_df["Enterprise_Actual"] + revenue_df["SMB_Actual"] + revenue_df["Services_Actual"]
    revenue_df["Total_Budget"] = revenue_df["Enterprise_Budget"] + revenue_df["SMB_Budget"] + revenue_df["Services_Budget"]
    
    fig_rev = go.Figure()
    fig_rev.add_trace(go.Scatter(x=revenue_df["Month"], y=revenue_df["Total_Actual"],
        name="Actual", line=dict(color="#2563EB", width=3)))
    fig_rev.add_trace(go.Scatter(x=revenue_df["Month"], y=revenue_df["Total_Budget"],
        name="Budget", line=dict(color="#94A3B8", width=2, dash="dash")))
    fig_rev.update_layout(title="Total Revenue: Actual vs Budget ($K)",
        plot_bgcolor="white", height=350)
    st.plotly_chart(fig_rev, use_container_width=True)

with col_right:
    latest = revenue_df.iloc[-1]
    seg_df = pd.DataFrame({
        "Segment": ["Enterprise", "SMB", "Services"],
        "Revenue": [latest["Enterprise_Actual"], latest["SMB_Actual"], latest["Services_Actual"]]
    })
    fig_seg = px.pie(seg_df, values="Revenue", names="Segment",
        title="Revenue Mix — Latest Month",
        color_discrete_sequence=["#2563EB","#3B82F6","#93C5FD"])
    fig_seg.update_layout(height=350)
    st.plotly_chart(fig_seg, use_container_width=True)

st.divider()

# ── EXPENSE CHARTS ──
st.markdown("### Expense Analysis")
col_left2, col_right2 = st.columns(2)

with col_left2:
    expense_df["Total_Actual"] = (expense_df["Headcount_Actual"] + expense_df["Marketing_Actual"] +
                                   expense_df["Operations_Actual"] + expense_df["Tech_Actual"])
    expense_df["Total_Budget"] = (expense_df["Headcount_Budget"] + expense_df["Marketing_Budget"] +
                                   expense_df["Operations_Budget"] + expense_df["Tech_Budget"])
    
    fig_exp = go.Figure()
    fig_exp.add_trace(go.Bar(x=expense_df["Month"], y=expense_df["Total_Actual"],
        name="Actual", marker_color="#EF4444"))
    fig_exp.add_trace(go.Bar(x=expense_df["Month"], y=expense_df["Total_Budget"],
        name="Budget", marker_color="#FCA5A5"))
    fig_exp.update_layout(title="Total Expenses: Actual vs Budget ($K)",
        barmode="group", plot_bgcolor="white", height=350)
    st.plotly_chart(fig_exp, use_container_width=True)

with col_right2:
    latest_exp = expense_df.iloc[-1]
    exp_df = pd.DataFrame({
        "Department": ["Headcount", "Marketing", "Operations", "Tech"],
        "Expense": [latest_exp["Headcount_Actual"], latest_exp["Marketing_Actual"],
                    latest_exp["Operations_Actual"], latest_exp["Tech_Actual"]]
    })
    fig_exp_bar = px.bar(exp_df, x="Department", y="Expense",
        title="Expense Breakdown by Department ($K)",
        color="Department",
        color_discrete_sequence=["#EF4444","#F97316","#EAB308","#8B5CF6"])
    fig_exp_bar.update_layout(plot_bgcolor="white", height=350, showlegend=False)
    st.plotly_chart(fig_exp_bar, use_container_width=True)

st.divider()

# ── VARIANCE TABLE ──
st.markdown("### Variance Summary")

latest_rev = revenue_df.iloc[-1]
prior_rev = revenue_df.iloc[-2]

variance_data = {
    "Line Item": ["Enterprise Revenue", "SMB Revenue", "Services Revenue", "Total Revenue"],
    "Actual ($K)": [latest_rev["Enterprise_Actual"], latest_rev["SMB_Actual"],
                    latest_rev["Services_Actual"], latest_rev["Total_Actual"]],
    "Budget ($K)": [latest_rev["Enterprise_Budget"], latest_rev["SMB_Budget"],
                    latest_rev["Services_Budget"], latest_rev["Total_Budget"]],
    "Prior Month ($K)": [prior_rev["Enterprise_Actual"], prior_rev["SMB_Actual"],
                          prior_rev["Services_Actual"], prior_rev["Total_Actual"]],
}

var_df = pd.DataFrame(variance_data)
var_df["vs Budget ($K)"] = var_df["Actual ($K)"] - var_df["Budget ($K)"]
var_df["vs Budget (%)"] = ((var_df["Actual ($K)"] - var_df["Budget ($K)"]) / var_df["Budget ($K)"] * 100).round(1)
var_df["vs Prior Month ($K)"] = var_df["Actual ($K)"] - var_df["Prior Month ($K)"]

st.dataframe(var_df, use_container_width=True, hide_index=True)

st.divider()

# ── AI COMMENTARY ──
st.markdown("### AI-Generated Executive Commentary")

if st.button("Generate AI Commentary", type="primary"):
    with st.spinner("Analyzing financials and generating commentary..."):
        
        summary = f"""
        Company: {company_name}
        Reporting Month: {selected_month} 2025
        
        REVENUE:
        - Enterprise: Actual ${latest_rev['Enterprise_Actual']}K vs Budget ${latest_rev['Enterprise_Budget']}K
        - SMB: Actual ${latest_rev['SMB_Actual']}K vs Budget ${latest_rev['SMB_Budget']}K  
        - Services: Actual ${latest_rev['Services_Actual']}K vs Budget ${latest_rev['Services_Budget']}K
        - Total Revenue: Actual ${latest_rev['Total_Actual']}K vs Budget ${latest_rev['Total_Budget']}K
        
        EXPENSES (latest month):
        - Headcount: Actual ${latest_exp['Headcount_Actual']}K vs Budget ${latest_exp['Headcount_Budget']}K
        - Marketing: Actual ${latest_exp['Marketing_Actual']}K vs Budget ${latest_exp['Marketing_Budget']}K
        - Operations: Actual ${latest_exp['Operations_Actual']}K vs Budget ${latest_exp['Operations_Budget']}K
        - Tech: Actual ${latest_exp['Tech_Actual']}K vs Budget ${latest_exp['Tech_Budget']}K
        
        KPIs:
        - Gross Margin: {kpi_df.iloc[0]['Actual']}% (Budget: {kpi_df.iloc[0]['Budget']}%)
        - EBITDA Margin: {kpi_df.iloc[1]['Actual']}% (Budget: {kpi_df.iloc[1]['Budget']}%)
        - Headcount: {kpi_df.iloc[2]['Actual']} (Budget: {kpi_df.iloc[2]['Budget']})
        """
        
        response = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=1000,
            messages=[{
                "role": "user",
                "content": f"""You are a senior FP&A analyst writing an executive commentary for a Monthly Business Review.
                
Write a professional 4-paragraph narrative based on this financial data:

{summary}

Structure it as:
1. Revenue Performance — headline results and key drivers
2. Expense Management — cost performance vs budget
3. KPI Highlights — margins and operational metrics
4. Outlook — one forward-looking sentence

Use specific numbers. Sound like a real CFO report. Be concise and professional."""
            }]
        )
        
        commentary = response.content[0].text
        st.session_state["commentary"] = commentary

if "commentary" in st.session_state:
    st.write(st.session_state["commentary"])

    st.divider()
    st.markdown("### Export Report")

    pdf_buffer = generate_pdf(
        company_name, selected_month,
        revenue_df, expense_df, kpi_df,
        st.session_state["commentary"]
    )

    st.download_button(
        label="📄 Download PDF Report",
        data=pdf_buffer,
        file_name=f"{company_name}_{selected_month}_2025_MBR.pdf",
        mime="application/pdf",
        type="primary"
    )